logger:
  default: info
  logs:
    com.dfi: trace
    com.dfi.sbc2ha.components.platform.mqtt: warn
    com.diozero.sbc.LocalSystemInfo: error
    com.dfi.sbc2ha.actuator.Led: trace
    com.diozero.devices.PwmLed: trace
    com.dfi.sbc2ha.actuator.LedFading: trace
    com.diozero.devices.PwmFadingLed: debug
  writer:
    format: "{ date:HH:mm:ss } {level|size=5} {class-name} {message}"
extension_boards:
  vendor: rpi
  inputBoard: nohat
  outputBoard: nohat
